# Generated by Django 6.0.3 on 2026-03-07 06:51

import backend.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('date', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('highlights', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=backend.models.getFileName)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('participants', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(default='', max_length=100)),
                ('venue', models.CharField(default='Virtual Event', max_length=255)),
                ('description', models.TextField(default='')),
                ('short_info', models.TextField(default='')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=backend.models.getFileName)),
                ('linkedin', models.URLField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('attendees', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to=backend.models.getFileName)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('webdev', 'Web Development'), ('dataanalytics', 'Data Analytics'), ('machinelearning', 'Machine Learning'), ('datasecurity', 'Data Security'), ('cloudcomputing', 'Cloud Computing'), ('design', 'Design & Media'), ('cinematography', 'Cinematography'), ('iot', 'IoT & Hardware'), ('bi', 'Business Intelligence'), ('management', 'Management'), ('event', 'Event Management'), ('pr', 'Public Relations')], max_length=50)),
                ('image', models.ImageField(upload_to=backend.models.getFileName)),
                ('linkedin', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=backend.models.getFileName)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.galleryevent')),
            ],
        ),
    ]
