# Generated by Django 6.0.3 on 2026-03-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_executive_position_alter_teammember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
