# Generated by Django 6.0.3 on 2026-03-07 08:34

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('venue', models.CharField(default='Virtual Event', max_length=255)),
                ('description', models.TextField()),
                ('short_info', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=backend.models.getFileName)),
                ('link', models.URLField(blank=True, help_text='Registration link', max_length=500)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
