# Generated by Django 5.0 on 2026-03-10 16:20

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_upcomingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('executive', 'Executive'), ('teammember', 'Team Member')], default='teammember', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=backend.models.getFileName)),
                ('linkedin', models.URLField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Ordering for display')),
                ('position', models.CharField(choices=[('president', 'President'), ('vice-president', 'Vice-President'), ('secretary', 'Secretary'), ('ceo', 'CEO'), ('hr', 'HR'), ('none', 'None')], default='none', max_length=100)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('co-lead', 'Co-lead'), ('associate', 'Associate'), ('none', 'None')], default='none', max_length=100)),
                ('domain', models.CharField(choices=[('webdev', 'Web Development'), ('dataanalytics', 'Data Analytics'), ('machinelearning', 'Machine Learning'), ('datasecurity', 'Data Security'), ('cloudcomputing', 'Cloud Computing'), ('design', 'Design & Media'), ('cinematography', 'Cinematography'), ('iot', 'IoT & Hardware'), ('bi', 'Business Intelligence'), ('management', 'Management'), ('event', 'Event Management'), ('pr', 'Public Relations'), ('none', 'None')], default='none', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Executive',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
