# Generated by Django 5.0 on 2026-03-23 06:57

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_member_delete_executive_delete_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Service', max_length=255)),
                ('image', models.ImageField(upload_to=backend.models.getFileName)),
                ('url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
