# Generated by Django 5.0 on 2026-03-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team_tab',
            field=models.IntegerField(choices=[(1, 'Tab 1'), (2, 'Tab 2')], default=1),
        ),
    ]
