# Generated by Django 5.0 on 2026-03-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_member_team_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab1Member',
            fields=[
            ],
            options={
                'verbose_name': 'Previous Tenure',
                'verbose_name_plural': 'Previous Tenure',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.member',),
        ),
        migrations.CreateModel(
            name='Tab2Member',
            fields=[
            ],
            options={
                'verbose_name': 'Current Tenure',
                'verbose_name_plural': 'Current Tenure',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.member',),
        ),
        migrations.AlterField(
            model_name='member',
            name='team_tab',
            field=models.IntegerField(choices=[(1, 'Previous Tenure'), (2, 'Current Tenure')], default=1),
        ),
    ]
