# Generated by Django 5.0 on 2026-03-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_tab1member_tab2member_alter_member_team_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Team Member', 'Team Member')], default='Team Member', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='domain',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Data Analytics', 'Data Analytics'), ('Machine Learning', 'Machine Learning'), ('Data Security', 'Data Security'), ('Cloud Computing', 'Cloud Computing'), ('Design & Media', 'Design & Media'), ('Cinematography', 'Cinematography'), ('IoT & Hardware', 'IoT & Hardware'), ('Business Intelligence', 'Business Intelligence'), ('Management', 'Management'), ('Event Management', 'Event Management'), ('Public Relations', 'Public Relations'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice-President', 'Vice-President'), ('Secretary', 'Secretary'), ('CEO', 'CEO'), ('HR', 'HR'), ('None', 'None')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Co-lead', 'Co-lead'), ('Associate', 'Associate'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
