# Generated by Django 5.0 on 2026-03-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_ourstory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourstory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='ourstory',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
    ]
