# Generated by Django 5.0 on 2026-03-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_ourstory_options_ourstory_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='galleryevent',
            options={'verbose_name': 'Gallery Event', 'verbose_name_plural': 'Gallery Events'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='ourstory',
            options={'ordering': ['order'], 'verbose_name': 'Our Story', 'verbose_name_plural': 'Our Story Entries'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='successstory',
            options={'verbose_name': 'Success Story', 'verbose_name_plural': 'Success Stories'},
        ),
        migrations.AlterModelOptions(
            name='upcomingevent',
            options={'verbose_name': 'Upcoming Event', 'verbose_name_plural': 'Upcoming Events'},
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower = first)'),
        ),
    ]
