# Generated by Django 5.0 on 2026-03-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_faq_alter_events_options_alter_galleryevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('portfolio_url', models.URLField(max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
                'ordering': ['order'],
            },
        ),
    ]
