# Generated by Django 5.0 on 2026-03-24 10:52

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_developer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.AddField(
            model_name='events',
            name='report',
            field=models.FileField(blank=True, help_text='Event report file (PDF, etc.)', null=True, upload_to=backend.models.getFileName),
        ),
    ]
