# Generated by Django 5.2.16 on 2026-07-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_delete_developer_events_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab1Coordinator',
            fields=[
            ],
            options={
                'verbose_name': 'Previous Tenure Coordinator',
                'verbose_name_plural': 'Previous Tenure Coordinators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.member',),
        ),
        migrations.CreateModel(
            name='Tab2Coordinator',
            fields=[
            ],
            options={
                'verbose_name': 'Current Tenure Coordinator',
                'verbose_name_plural': 'Current Tenure Coordinators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.member',),
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Club Coordinator', 'Club Coordinator'), ('Team Member', 'Team Member')], default='Team Member', max_length=20),
        ),
    ]
