# Generated by Django 5.2.16 on 2026-07-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_tab1coordinator_tab2coordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='domain',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Data Analytics', 'Data Analytics'), ('Machine Learning', 'Machine Learning'), ('Data Engineering', 'Data Engineering'), ('Generative AI', 'Generative AI'), ('Data Security', 'Data Security'), ('Cloud Computing', 'Cloud Computing'), ('Design & Media', 'Design & Media'), ('Cinematography', 'Cinematography'), ('IoT & Hardware', 'IoT & Hardware'), ('Business Intelligence', 'Business Intelligence'), ('Management', 'Management'), ('Event Management', 'Event Management'), ('Public Relations', 'Public Relations'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice-President', 'Vice-President'), ('Secretary', 'Secretary'), ('CEO', 'CEO'), ('HR', 'HR'), ('Head of Operations', 'Head of Operations'), ('Coordinator', 'Coordinator'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
